linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
linters:
  enable:
    - errcheck
    - unused
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - revive
